CREATE DATABASE india_energy;
USE india_energy;

CREATE TABLE staging_energy_raw (
    row_id INT,
    year INT,
    entity VARCHAR(50),
    code VARCHAR(10),
    oil_consumption_ej DECIMAL(12,4),
    gas_consumption_ej DECIMAL(12,4),
    coal_consumption_ej DECIMAL(12,4),
    solar_consumption_ej DECIMAL(12,4),
    hydro_consumption_ej DECIMAL(12,4),
    nuclear_consumption_ej DECIMAL(12,4),
    wind_consumption_ej DECIMAL(12,4),
    geo_biomass_other_ej DECIMAL(12,4),
    biofuels_twh DECIMAL(12,4),
    clean_cooking_access_pct DECIMAL(6,3),
    annual_change_primary_energy_pct DECIMAL(8,4),
    co2_per_kwh DECIMAL(8,4),
    electricity_generation_twh DECIMAL(12,4),
    elec_coal_twh DECIMAL(12,4),
    elec_gas_twh DECIMAL(12,4),
    elec_hydro_twh DECIMAL(12,4),
    elec_other_renew_twh DECIMAL(12,4),
    elec_solar_twh DECIMAL(12,4),
    elec_oil_twh DECIMAL(12,4),
    elec_wind_twh DECIMAL(12,4),
    elec_nuclear_twh DECIMAL(12,4),
    energy_per_gdp_kwh DECIMAL(10,4),
    fossil_pct_subenergy DECIMAL(6,3),
    lowcarbon_pct_subenergy DECIMAL(6,3),
    nuclear_pct_subenergy DECIMAL(6,3),
    per_capita_elec_kwh DECIMAL(10,3),
    energy_per_capita_kwh DECIMAL(10,3),
    primary_energy_twh DECIMAL(12,4),
    coal_pct_elec DECIMAL(6,3),
    gas_pct_elec DECIMAL(6,3),
    hydro_pct_elec DECIMAL(6,3),
    solar_pct_elec DECIMAL(6,3),
    wind_pct_elec DECIMAL(6,3),
    oil_pct_elec DECIMAL(6,3),
    nuclear_pct_elec DECIMAL(6,3),
    other_renew_pct_elec DECIMAL(6,3),
    fossil_pct_elec DECIMAL(6,3),
    lowcarbon_pct_elec DECIMAL(6,3),
    nuclear_pct_elec_dup DECIMAL(6,3),  
    renewables_pct_elec DECIMAL(6,3),
    access_electricity_pct DECIMAL(6,3)
);

SHOW DATABASES LIKE 'india_energy';